# Site Settings
title:               Millennial
tagline:             a Jekyll theme
description:
baseurl:            #"/Millennial"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Millennial"
author:
  name:              "Kiva Uhuru"
  email:             "kiva.uhuru@berkeley.edu"
  twitter:           "AndKompany"
  instagram:         "woodywalken"
  github:            "KivaUhuru"
  facebook:          "Kiva.uhuru"
  linkedin:          "kiva-uhuru"
  
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
